### ISSUE TITLE
BUG: Fix frontend start and build process

### ISSUE THREAD

**Issue by HarshCasper** [moja-global/FLINT.Reporting#14]
## Describe the bug

While doing a `npm start` or `npm build` the following bug arises:

```sh
### INFO: Rendering /workspace/FLINT.Reporting/code/client/src/app/app.component.pug
### INFO: Rendering /workspace/FLINT.Reporting/code/client/src/modules/accountabilities-rules/components/accountabilities-rules-records-creation/accountabilities-rules-records-creation.component.pug
### INFO: Rendering /workspace/FLINT.Reporting/code/client/src/modules/accountabilities-rules/components/accountabilities-rules-records-deletion/accountabilities-rules-records-deletion.component.pug
### INFO: Rendering /workspace/FLINT.Reporting/code/client/src/modules/accountabilities-rules/components/accountabilities-rules-records-selection/accountabilities-rules-records-selection.component.pug
### INFO: Rendering /workspace/FLINT.Reporting/code/client/src/modules/accountabilities-rules/components/accountabilities-rules-records-tabulation/accountabilities-rules-records-tabulation.component.pug
### INFO: Rendering /workspace/FLINT.Reporting/code/client/src/modules/accountabilities-rules/containers/accountabilities-rules-records-creation-modal/accountabilities-rules-records-creation-modal.component.pug
### INFO: Rendering /workspace/FLINT.Reporting/code/client/src/modules/accountabilities-rules/containers/accountabilities-rules-records-deletion-modal/accountabilities-rules-records-deletion-modal.component.pug
### INFO: Rendering /workspace/FLINT.Reporting/code/client/src/modules/accountabilities-rules/containers/accountabilities-rules-records-home-page/accountabilities-rules-records-home-page.component.pug
### INFO: Rendering /workspace/FLINT.Reporting/code/client/src/modules/accountabilities-rules/containers/accountabilities-rules-records-selection-page/accountabilities-rules-records-selection-page.component.pug
### INFO: Rendering /workspace/FLINT.Reporting/code/client/src/modules/accountabilities-rules/containers/accountabilities-rules-records-tabulation-page/accountabilities-rules-records-tabulation-page.component.pug
### INFO: Rendering /workspace/FLINT.Reporting/code/client/src/modules/accountabilities-types/components/accountabilities-types-records-creation/accountabilities-types-records-creation.component.pug
### INFO: Rendering /workspace/FLINT.Reporting/code/client/src/modules/accountabilities-types/components/accountabilities-types-records-deletion/accountabilities-types-records-deletion.component.pug
### INFO: Rendering /workspace/FLINT.Reporting/code/client/src/modules/accountabilities-types/components/accountabilities-types-records-selection/accountabilities-types-records-selection.component.pug
### INFO: Rendering /workspace/FLINT.Reporting/code/client/src/modules/accountabilities-types/components/accountabilities-types-records-tabulation/accountabilities-types-records-tabulation.component.pug
### INFO: Rendering /workspace/FLINT.Reporting/code/client/src/modules/accountabilities-types/components/accountabilities-types-records-updation/accountabilities-types-records-updation.component.pug
### INFO: Rendering /workspace/FLINT.Reporting/code/client/src/modules/accountabilities-types/containers/accountabilities-types-records-creation-modal/accountabilities-types-records-creation-modal.component.pug
### INFO: Rendering /workspace/FLINT.Reporting/code/client/src/modules/accountabilities-types/containers/accountabilities-types-records-deletion-modal/accountabilities-types-records-deletion-modal.component.pug
### INFO: Rendering /workspace/FLINT.Reporting/code/client/src/modules/accountabilities-types/containers/accountabilities-types-records-home-page/accountabilities-types-records-home-page.component.pug
### INFO: Rendering /workspace/FLINT.Reporting/code/client/src/modules/accountabilities-types/containers/accountabilities-types-records-selection-page/accountabilities-types-records-selection-page.component.pug
### INFO: Rendering /workspace/FLINT.Reporting/code/client/src/modules/accountabilities-types/containers/accountabilities-types-records-tabulation-page/accountabilities-types-records-tabulation-page.component.pug
### INFO: Rendering /workspace/FLINT.Reporting/code/client/src/modules/accountabilities-types/containers/accountabilities-types-records-updation-modal/accountabilities-types-records-updation-modal.component.pug
### INFO: Rendering /workspace/FLINT.Reporting/code/client/src/modules/accountabilities/components/accountabilities-records-creation/accountabilities-records-creation.component.pug
### INFO: Rendering /workspace/FLINT.Reporting/code/client/src/modules/accountabilities/components/accountabilities-records-deletion/accountabilities-records-deletion.component.pug
### INFO: Rendering /workspace/FLINT.Reporting/code/client/src/modules/accountabilities/components/accountabilities-records-selection/accountabilities-records-selection.component.pug
### INFO: Rendering /workspace/FLINT.Reporting/code/client/src/modules/accountabilities/components/accountabilities-records-tabulation/accountabilities-records-tabulation.component.pug
### INFO: Rendering /workspace/FLINT.Reporting/code/client/src/modules/accountabilities/containers/accountabilities-records-creation-modal/accountabilities-records-creation-modal.component.pug
### INFO: Rendering /workspace/FLINT.Reporting/code/client/src/modules/accountabilities/containers/accountabilities-records-deletion-modal/accountabilities-records-deletion-modal.component.pug
### INFO: Rendering /workspace/FLINT.Reporting/code/client/src/modules/accountabilities/containers/accountabilities-records-home-page/accountabilities-records-home-page.component.pug
### INFO: Rendering /workspace/FLINT.Reporting/code/client/src/modules/accountabilities/containers/accountabilities-records-selection-page/accountabilities-records-selection-page.component.pug
### INFO: Rendering /workspace/FLINT.Reporting/code/client/src/modules/accountabilities/containers/accountabilities-records-tabulation-page/accountabilities-records-tabulation-page.component.pug
### INFO: Rendering /workspace/FLINT.Reporting/code/client/src/modules/actors/containers/actors-dashboard/actors-dashboard.component.pug
/workspace/FLINT.Reporting/code/client/node_modules/pug/node_modules/pug-lexer/index.js:68
    throw err;
    ^

Error: /workspace/FLINT.Reporting/code/client/src/modules/actors/containers/actors-dashboard/actors-dashboard.component.pug:10:1
    8|       .card-body
    9|         sb-actors-records-tabulation([pagesize]='6')
  > 10| 
--------^

The end of the string reached with no closing bracket ) found.
    at makeError (/workspace/FLINT.Reporting/code/client/node_modules/pug/node_modules/pug-error/index.js:34:13)
    at Lexer.error (/workspace/FLINT.Reporting/code/client/node_modules/pug/node_modules/pug-lexer/index.js:62:15)
    at Lexer.bracketExpression (/workspace/FLINT.Reporting/code/client/node_modules/pug/node_modules/pug-lexer/index.js:274:14)
    at Lexer.attrs (/workspace/FLINT.Reporting/code/client/node_modules/pug/node_modules/pug-lexer/index.js:1445:24)
    at Lexer.callLexerFunction (/workspace/FLINT.Reporting/code/client/node_modules/pug/node_modules/pug-lexer/index.js:1647:23)
    at Lexer.advance (/workspace/FLINT.Reporting/code/client/node_modules/pug/node_modules/pug-lexer/index.js:1686:12)
    at Lexer.callLexerFunction (/workspace/FLINT.Reporting/code/client/node_modules/pug/node_modules/pug-lexer/index.js:1647:23)
    at Lexer.getTokens (/workspace/FLINT.Reporting/code/client/node_modules/pug/node_modules/pug-lexer/index.js:1706:12)
    at lex (/workspace/FLINT.Reporting/code/client/node_modules/pug/node_modules/pug-lexer/index.js:12:42)
    at Object.lex (/workspace/FLINT.Reporting/code/client/node_modules/pug/lib/index.js:104:9) {
  code: 'PUG:NO_END_BRACKET',
  msg: 'The end of the string reached with no closing bracket ) found.',
  line: 10,
  column: 1,
  filename: '/workspace/FLINT.Reporting/code/client/src/modules/actors/containers/actors-dashboard/actors-dashboard.component.pug',
  src: 'sb-layout-main\n' +
    '  ng-container(header)\n' +
    "    sb-header(title='Actors', subtitle='The supported reporting structures')\n" +
    "  ng-container(body')\n" +
    '    sb-card\n' +
    '      .card-header\n' +
    '        | Actors List\n' +
    '      .card-body\n' +
    "        sb-actors-records-tabulation([pagesize]='6')\n",
  toJSON: [Function (anonymous)]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## To Reproduce**
1. Go to 'code/client` directory
2. Install the packages by running `npm install`
3. Run `npm start` or `npm build`
4. Check the stacktrace to find the error.

## Expected behavior**

We would ideally like the front end to build successfully.

**Comment by asmijafar20** [comment]
I have tried my hands on this issue. But after running `npm start` 200 files get changed (.pug files). Also the `http://localhost:4200/#/` is a blank page but `http://localhost:4200/#/dashboard` works fine.

**Comment by AayushSaini101** [comment]
@asmijafar20  How to discard changes
